version: '3.9'
name: exchange_rates_service
services:

  exchange_rates_db:
    hostname: exchange_rates_db
    container_name: exchange_rates_db
    image: postgres
    command: [ "postgres", "-c", "max_prepared_transactions=200" ]
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_DB_LOGIN}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB_PORT} -U $${POSTGRES_DB_LOGIN}" ]
      timeout: 2s
      retries: 15

  exchange_rate_service:
    container_name: exchange_rate_service
    restart: unless-stopped
    working_dir: /code/src
    command: uvicorn --log-level debug app.main:app --host $APP_HOST --port $APP_PORT --reload
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      exchange_rates_db:
        condition:
          service_healthy
      redis:
        condition:
          service_healthy
      rabbitmq:
        condition:
          service_healthy
    environment:
      - APP_HOST
      - APP_PORT
      - POSTGRES_DB_LOGIN
      - POSTGRES_DB_PASSWORD
      - POSTGRES_DB_HOST
      - POSTGRES_DB_PORT
      - POSTGRES_DB_NAME
      - SQLALCHEMY_ECHO
      - SQLALCHEMY_POOL_SIZE
      - REDIS_URL
      - RABBITMQ_QUEUE_NAME
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD
      - RABBITMQ_HOST
      - LOGGING_LEVEL
    ports:
      - "8000:8000"
    volumes:
      - ../src:/code/src

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.12-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3


  nginx_service:
    image: nginx:latest
    container_name: nginx_service
    ports:
      - "80:80"
    volumes:
      - ../nginx:/etc/nginx/conf.d
    depends_on:
      - exchange_rate_service

  redis:
    container_name: redis
    hostname: ${REDIS_HOST}
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3